### ISSUE TITLE
HGPyroIronMONV0.1.0.FL Patch file seems to be broken

### ISSUE THREAD

**Issue by danielabdalla** [PyroMikeGit/IronMONHGSS#1]
When patching the original HG ROM with the HGPyroIronMONV0.1.0.FL patch file, the game does not load when generating seeds (Kaizo), instead there is a white screen that persists.

Testing with the other patch HGPyroIronMONV0.1.0 works as expected.

**Comment by PyroMikeGit** [comment]
Accidently messed with the wrong memory values when adding the frame limiter back in. Just uploaded the fixed version now to the latest release.
